[2021-07-20 17:10:58,052] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:10:58,078] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:10:58,079] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:10:58,079] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:10:58,079] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:10:58,173] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse7> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:10:58,180] {standard_task_runner.py:52} INFO - Started process 420880 to run task
[2021-07-20 17:10:58,198] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse7', '2021-07-19T00:00:00+00:00', '--job-id', '303', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpx0rz2icg', '--error-file', '/tmp/tmppt8f_opa']
[2021-07-20 17:10:58,200] {standard_task_runner.py:77} INFO - Job 303: Subtask fuse7
[2021-07-20 17:10:58,375] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:10:58,659] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse7
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:37:17,411] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/deepika/airflow/dags/dag.py", line 27, in fuse_task7
    load_df(task7(), 7)
  File "/home/deepika/airflow/dags/main.py", line 24, in load_df
    df.write.jdbc(url=url,
  File "/opt/spark/python/pyspark/sql/readwriter.py", line 1445, in jdbc
    self.mode(mode)._jwrite.jdbc(url, table, jprop)
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o144.jdbc.
: org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 110789 tasks (1024.0 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:854)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:63)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:301)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:817)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)

[2021-07-20 17:37:17,530] {taskinstance.py:1524} INFO - Marking task as UP_FOR_RETRY. dag_id=Fuse, task_id=fuse7, execution_date=20210719T000000, start_date=20210720T112558, end_date=20210720T115217
[2021-07-20 17:37:17,711] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-07-20 18:07:17,925] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:07:17,935] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:07:17,935] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:07:17,935] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:07:17,935] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:07:18,007] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse7> on 2021-07-19T00:00:00+00:00
[2021-07-20 18:07:18,012] {standard_task_runner.py:52} INFO - Started process 548422 to run task
[2021-07-20 18:07:18,022] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse7', '2021-07-19T00:00:00+00:00', '--job-id', '303', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfmon49ke', '--error-file', '/tmp/tmpqx13a5mu']
[2021-07-20 18:07:18,023] {standard_task_runner.py:77} INFO - Job 303: Subtask fuse7
[2021-07-20 18:07:19,264] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse7 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:07:19,552] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse7
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 18:38:09,692] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:38:09,746] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse7, execution_date=20210719T000000, start_date=20210720T122217, end_date=20210720T125309
[2021-07-20 18:38:09,969] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:38:10,009] {local_task_job.py:151} INFO - Task exited with return code 0
